language: ruby
script: "bundle exec rake spec:all"
rvm:
  - jruby-head
  - jruby-9.0.5.0
  - jruby-9.1.1.0
  - jruby-1.7.25
jdk:
  - openjdk7
  - oraclejdk8
matrix:
  allow_failures:
    - rvm: jruby-head
  fast_finish: true
notifications:
  irc: "irc.freenode.org#shoes"
  email:
    recipients:
      - davor@davor.se
      - wasnotrice@gmail.com
      - pragtob@gmail.com
      - ashbbb@gmail.com
      - james@jamesrgifford.com
      - peter.fitzgibbons@gmail.com
      - fism88@gmail.com
      - jason@jasonrclark.net
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
before_script:
  - "export DISPLAY=:99.0"
  - "export SWT_GTK3=0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle update" # recommended for caching for now see #981 for info
  - "sleep 3"
after_script:
  - find -name '*.log' -exec cat {} \;
sudo: false # new build environment
cache: bundler
addons:
  code_climate:
    repo_token: 45d4f3c5c1de9031011acf4c3c85867f152cea4200c61f3b69d881bcf2794e9f
